import { createContext, useState } from "react";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { ThemeProvider } from "@mui/material/styles";
import themes from "../themes/index";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import contextType from "@/types/contenxt";
import { context } from "@/context";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer, toast } from "react-toastify";

export default function App({ Component, pageProps }: AppProps) {
  const [state, setState] = useState<contextType>({
    save_product: false,
    maxWidth: { xs: "100%", xl: "1536px" },
    px: { xs: 2, md: 4 },
    margin: "200px auto 0 auto",
    user_detail: {
      username: "",
      family: "",
      department: "",
      role: "",
    },
  });
  return (
    <>
      <Head>
        <title>تالار ملک</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <context.Provider value={{ state, setState }}>
        <ThemeProvider theme={themes}>
          <Component {...pageProps} />
          <ToastContainer />
        </ThemeProvider>
      </context.Provider>
    </>
  );
}
