import productType from "@/types/product";

export const product_item: productType[] = [
  {
    title: "واحد تجاری طبقه اول",
    city: "تهران",
    meter: "200 متر",
    image: "/images/product/product1.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک تجاری",
    id: 1,
    introduction_code: 21235,
    price: "50000000",
    liked: false,
    is_selled: false,
  },
  {
    title: "دفتر اداری مجهز",
    city: "مشهد",
    meter: "700 متر",
    image: "/images/product/product2.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک اداری",
    id: 2,
    introduction_code: 21235,
    price: "35000000",
    liked: false,
    is_selled: false,
  },
  {
    title: "زمین کشاورزی",
    city: "رشت",
    meter: "4 هکتار",
    image: "/images/product/product3.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک کشاورزی",
    id: 3,
    introduction_code: 21235,
    price: "1200000",
    liked: false,
    is_selled: false,
  },
  {
    title: "گلخانه کاشت توت فرنگی",
    city: "مازندران",
    meter: "1200 متر",
    image: "/images/product/product4.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک کشاورزی",
    id: 4,
    introduction_code: 21235,
    price: "800000",
    liked: false,
    is_selled: false,
  },
  {
    title: "ساختمان اداری",
    city: "تهران",
    meter: "1200 متر",
    image: "/images/product/product5.webp",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک اداری",
    id: 5,
    introduction_code: 21235,
    price: "65000000",
    liked: false,
    is_selled: false,
  },
  {
    title: "زمین کشاورزی کشت گوجه ",
    city: "سمنان",
    meter: "9500 متر",
    image: "/images/product/product6.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک کشاورزی",
    id: 6,
    introduction_code: 21235,
    price: "74000000",
    liked: false,
    is_selled: true,
  },
  {
    title: "فروشگاه تجاری",
    city: "تبریز",
    meter: "4500 متر",
    image: "/images/product/product7.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک تجاری",
    id: 7,
    introduction_code: 21235,
    price: "8600000",
    liked: false,
    is_selled: false,
  },
  {
    title: "واحد دفتر اداری",
    city: "تهران",
    meter: "200 متر",
    image: "/images/product/product8.webp",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک اداری",
    id: 8,
    introduction_code: 21235,
    price: "7500000",
    liked: false,
    is_selled: false,
  },
  {
    title: "ملک اداری اخرین واحد",
    city: "اصفهان",
    meter: "7500 متر",
    image: "/images/product/product9.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک تجاری",
    id: 9,
    introduction_code: 21235,
    price: "7700000",
    liked: false,
    is_selled: false,
  },
  {
    title: "اداره مجهز و تازه ساخت",
    city: "تهران",
    meter: "800 متر",
    image: "/images/product/product10.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک اداری",
    id: 10,
    introduction_code: 21235,
    price: "9600000",
    liked: false,
    is_selled: false,
  },
  {
    title: "واحد تجاری طبقه اول",
    city: "تهران",
    meter: "200 متر",
    image: "/images/product/product1.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک تجاری",
    id: 11,
    introduction_code: 21235,
    price: "50000000",
    liked: false,
    is_selled: false,
  },
  {
    title: "زمین کشاورزی کشت گوجه ",
    city: "سمنان",
    meter: "95000000 متر",
    image: "/images/product/product6.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک کشاورزی",
    id: 12,
    introduction_code: 21235,
    price: "74000000",
    liked: false,
    is_selled: false,
  },
  {
    title: "گلخانه کاشت توت فرنگی",
    city: "مازندران",
    meter: "1200 متر",
    image: "/images/product/product4.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک کشاورزی",
    id: 13,
    introduction_code: 21235,
    price: "800000",
    liked: false,
    is_selled: true,
  },
  {
    title: "واحد تجاری طبقه اول",
    city: "تهران",
    meter: "200 متر",
    image: "/images/product/product1.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک تجاری",
    id: 14,
    introduction_code: 21235,
    price: "50000000",
    liked: false,
    is_selled: false,
  },
  {
    title: "زمین کشاورزی",
    city: "رشت",
    meter: "4 هکتار",
    image: "/images/product/product3.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک کشاورزی",
    id: 15,
    introduction_code: 21235,
    price: "1200000",
    liked: false,
    is_selled: false,
  },
  {
    title: "واحد تجاری طبقه اول",
    city: "تهران",
    meter: "200 متر",
    image: "/images/product/product1.jpeg",
    description:
      "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله ",
    type: "ملک تجاری",
    id: 16,
    introduction_code: 21235,
    price: "50000000",
    liked: false,
    is_selled: true,
  },
];
